server:
  port: 8082

spring:
  application:
    name: sly-water-8082
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterUnicoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    druid:
        max-active: 10
        min-idle: 5
        max-wait: 3000

  # MyBatis配置信息
mybatis:
  # 配置包名称别名
  type-aliases-package: com.sly.springboot.entities
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/*Mapper.xml
